name: windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: perl -V
        run: perl -V
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: gmake
        run: gmake
      - name: gmake disttest
        run: gmake disttest
